### ISSUE TITLE
[FEATURE]: What file is the front-end page design for image search

### ISSUE THREAD

**Issue by listento123** [milvus-io/bootcamp#1335] opened 2024-05-25 08:38 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

I would like to know which file is the front-end page design for the image search system built in this folder, and I would like to design the front-end page for this system
The specific file path is as follows:
milvus-io/bootcamp/solutions/image_search2

### Describe the solution you'd like

Tell me directly which file it is in

**Comment by jaelgu** [comment] 2024-05-27 02:29
Duplicate of #1330

**Closed by jaelgu** 2024-05-27 02:29 UTC
